# .gitlab-ci.yml
image: rust:latest

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - target/
    - Cargo.lock

stages:
  - lint
  - test
  - snapshots


lint:
  stage: lint
  script:
    - rustup component add clippy rustfmt
    - cargo fmt -- --check
    - cargo clippy -- -D warnings
  allow_failure: true

test:
  stage: test
  script:
    - cargo install cargo-insta
    - CI=true cargo test -- --nocapture
  artifacts:
    paths:
      - tests/snapshots/
    when: on_failure
    expire_in: 1 week

review-snapshots:
  stage: snapshots
  script:
    - cargo install cargo-insta
    - cargo insta test --review --unreferenced=delete
    - git diff --exit-code tests/snapshots/ || echo "Snapshots changed!: cargo insta review"
  rules:
    - if: $CI_MERGE_REQUEST_IID
  allow_failure: true