image: rust:latest

stages:
  - lint
  - test

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - target/
    - Cargo.lock
    - .cargo/

.before_script:
  - rustup component add rustfmt clippy

lint:
  stage: lint
  script:
    - cargo fmt -- --check
    - cargo clippy -- -D warnings
  tags:
    - main
  allow_failure: true

test:
  stage: test
  script:
    - cargo install cargo-insta --locked || true
    - CI=true cargo test -- --nocapture
  tags:
    - main
  artifacts:
    paths:
      - tests/snapshots/
    when: on_failure
    expire_in: 1 week